import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import my_profile from '../public/my_profile.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>{process.env.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.image_wrapper}>
        <Image className={styles.image} src={my_profile} alt="my profile image" />
      </div>
      <p className={styles.user_name}>{process.env.name}</p>
      <a href="#" className={styles.links}>FACEBOOK</a>
      <a href="#" className={styles.links}>TWITTER</a>
      <a href="#" className={styles.links}>YOUTUBE</a>
    </div>
  )
}
